---
nodeLinker: pnp
npmRegistries:
  //registry.npmjs.org/:
    npmAuthToken: "${NPM_PUBLISH_TOKEN:-invalid}"

enableTransparentWorkspaces: false

logFilters:
  - pattern: "doesn't provide eslint-plugin-import (*), requested by eslint-import-resolver-typescript"
    level: discard
