---
nodeLinker: pnp

logFilters:
  - pattern: "doesn't provide eslint-plugin-import (*), requested by eslint-import-resolver-typescript"
    level: discard

supportedArchitectures:
  os:
    - current
    - darwin
    - linux

  cpu:
    - current
    - x86
    - x64
    - arm64
