enableScripts: true

logFilters:
  - level: discard
    pattern: "doesn't provide eslint-plugin-import (*), requested by eslint-import-resolver-typescript"

nodeLinker: pnp

npmMinimalAgeGate: 3d

supportedArchitectures:
  cpu:
    - current
    - x86
    - x64
    - arm64
  os:
    - current
    - darwin
    - linux
