---
name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: noahnu/.github/.github/actions/setup-node@main

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: [prepare]
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: noahnu/.github/.github/actions/setup-node@main

      - name: Run Lint
        run: |
          yarn lint:ci

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [prepare]
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: noahnu/.github/.github/actions/setup-node@main

      - name: Run Build
        run: |
          yarn build

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [prepare]
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: noahnu/.github/.github/actions/setup-node@main

      - name: Run Test
        run: |
          yarn test

  preview:
    name: Preview
    runs-on: ubuntu-latest
    needs: [prepare]
    if: "!contains(github.event.head_commit.message, '[skip ci]') && github.event_name == 'pull_request'"
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: noahnu/.github/.github/actions/setup-node@main

      - name: Post Preview
        uses: monoweave/github-action-preview@ba0d968e9a4a7a783dddcff1a0e1952b29fe49a9 # v1.1.1

  required_checks:
    name: Required Checks
    needs:
      - prepare
      - build
      - lint
      - test
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Fail on error
        if: contains(needs.*.result, 'failure') || cancelled()
        run: exit 1
