---
name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: noahnu/.github/.github/actions/setup-node@main

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: [prepare]
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: noahnu/.github/.github/actions/setup-node@main

      - name: Run Lint
        run: |
          yarn lint:ci

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [prepare]
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: noahnu/.github/.github/actions/setup-node@main

      - name: Run Build
        run: |
          yarn build

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [prepare]
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: noahnu/.github/.github/actions/setup-node@main

      - name: Run Test
        run: |
          yarn test

  preview:
    name: Preview
    runs-on: ubuntu-latest
    needs: [prepare]
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: noahnu/.github/.github/actions/setup-node@main

      - name: Post Monodeploy Preview
        uses: noahnu/.github/.github/actions/post-monodeploy-preview@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
